name: Bookstore API Automation
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build and Test
        run: mvn clean test
      - name: Generate Surefire HTML report
        if: always()
        run: mvn surefire-report:report-only
      - name: Upload Surefire HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-report
          path: target/reports/surefire.html